### ISSUE TITLE
CUDA Error 29: driver shutting down

### ISSUE THREAD

**Issue by talhachattha** [Xtra-Computing/thundergbm#22]
I get the following error at the end of my training for TGBMRegressor with default parameters, this doesn't allow the python process to release the GPU memory and it stays there.

2019-06-27 16:15:43,952 INFO [default] #instances = 1280, #features = 729
2019-06-27 16:15:44,031 INFO [default] copy csr matrix to GPU
2019-06-27 16:15:44,220 INFO [default] converting csr matrix to csc matrix
2019-06-27 16:15:44,483 INFO [default] Getting cut points...
2019-06-27 16:15:44,485 INFO [default] ################>>>: 1
2019-06-27 16:15:44,491 INFO [default]   ----------------->>> Last LOOP: 0.0072718
2019-06-27 16:15:44,494 INFO [default] TOTAL CP:152949
2019-06-27 16:15:45,617 INFO [default] RMSE = 3.72949
2019-06-27 16:15:45,645 INFO [default] RMSE = 3.3029
2019-06-27 16:15:45,672 INFO [default] RMSE = 2.93213
2019-06-27 16:15:45,673 INFO [default] training time = 1.17665
2019-06-27 16:15:45,711 INFO [default] #instances = 549, #features = 729
CUDA error 29 [D:\thundergbm\src\thundergbm\syncmem.cpp, 576]: driver shutting down
CUDA error 29 [D:\thundergbm\cub\cub/util_allocator.cuh, 657]: driver shutting down

**Comment by zeyiwen** [comment]
Please describe more details about your environment for running ThunderGBM. Also, how do you obtain ThunderGBM (e.g., using ``pip install``)? If you install ThunderGBM using ``pip``, please try to upgrade it to the lastest version.

**Comment by talhachattha** [comment]
I installed ThunderGBM from source with CUDA enabled, following are the details
I have a conda environment in Windows 10 with CUDA 10 installed.

Name: thundergbm
Version: 0.3.4
Summary: A Fast GBM Library on GPUs and CPUs
Home-page: https://github.com/zeyiwen/thundergbm
Author: None
Author-email: None
License: UNKNOWN
Location: c:\users\talhaa\.conda\envs\tf_env\lib\site-packages\thundergbm-0.3.4-py3.7.egg
Requires: numpy, scipy, scikit-learn

What other information is required?

**Comment by zeyiwen** [comment]
Would you please try ``pip install --upgrade thundergbm`` to upgrade to the latest version? The latest version of thundergbm on Pypi is 0.3.6. Yours is 0.3.4.

**Comment by Tripton** [comment]
I have the same problem on Windows 10 with CUDA 10. I use it with a GTX 1080 with driver version 431.86.
I build it from source.

Name: thundergbm
Version: 0.3.7
Summary: A Fast GBM Library on GPUs and CPUs
Home-page: https://github.com/zeyiwen/thundergbm
Author: Xtra Computing Group
Author-email: None
License: Apache-2.0
Location: c:\users\xxx\.conda\envs\sk\lib\site-packages\thundergbm-0.3.7-py3.7.egg
Requires: numpy, scipy, scikit-learn

I think it's not really a big problem, cause everything else exepect the end of my script works fine, but I saw this issue and thought that it maybe helps.

**Comment by zeyiwen** [comment]
Hmm. We have fixed the problem before, and will see what happens. But I am glad to know that it doesn't affect the final outcome which is the most important :)
